name: Gradle CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:

    name: Gradle-Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'zulu'
          cache: 'gradle'

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.5

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle (Init Project)
        run: ./gradlew build

      - name: Build Mirai Plugin
        run: ./gradlew buildPlugin

      - name: Upload Plugin Jar
        uses: actions/upload-artifact@v4
        with:
          name: mirai-plugin
          path: build/libs/*.jar
