name: Release CI

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag name for this release'
        required: true

jobs:
  release:

    name: Build and Release Plugin
    runs-on: ubuntu-latest

    env:
      VERSION: ${{ github.event.inputs.tag }}

    steps:
      # 1. Checkout the repository
      - name: Checkout
        uses: actions/checkout@v3

      # 2. Set up JDK 11
      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'zulu'
          cache: 'gradle'

      # 3. Gradle Wrapper Validation
      - name: Gradle Wrapper Validation
        uses: gradle/actions/wrapper-validation@v3

      # 4. Make gradlew executable
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # 5. Initialize the project and download dependencies
      - name: Build with Gradle (Init Project)
        run: ./gradlew build

      # 6. Build the plugin
      - name: Build Mirai Plugin
        run: ./gradlew buildPlugin

      # 7. Compress Source Code and Upload to Release
      - name: Create Source Code Archives
        run: |
          git archive --format=tar.gz -o "Source code.tar.gz" HEAD
          git archive --format=zip -o "Source code.zip" HEAD

      # 8. Create Git Release Tag
      - name: Create Git Tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag $VERSION
          git push origin $VERSION

      # 9. Create Release and Upload Artifacts
      - name: Create Release and Upload Artifacts
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          name: Release ${{ env.VERSION }}
          files: |
            build/mirai/*.jar
            Source code.zip
            Source code.tar.gz
          overwrite: true
