name: Gradle CI

on:
  workflow_dispatch:

jobs:
  release:

    name: Build and Release Plugin
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout
        uses: actions/checkout@v3

      # 2. Set up JDK 11
      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'zulu'
          cache: 'gradle'

      # 3. Gradle Wrapper Validation
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.5

      # 4. Make gradlew executable
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # 5. Initialize the project and download dependencies
      - name: Build with Gradle (Init Project)
        run: ./gradlew build

      # 6. Build the plugin
      - name: Build Mirai Plugin
        run: ./gradlew buildPlugin

      # 7. Read version from build.gradle.kts
      - name: Get Version from build.gradle.kts
        id: version
        run: |
          VERSION=$(grep 'version =' build.gradle.kts | awk '{print $3}' | tr -d '"')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # 8. Compress Source Code and Upload to Release
      - name: Compress Source Code and Upload
        run: |
          tar -czf "Source code.tar.gz" .
          zip -r "Source code.zip" .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 9. Create Release and Upload Artifacts
      - name: Create Release and Upload Artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/mirai/*.jar
            "Source code.zip"
            "Source code.tar.gz"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_NAME: ${{ env.VERSION }}
          TAG_NAME: v${{ env.VERSION }}
